### ISSUE TITLE
Taxonomy for the hierarchies

### ISSUE THREAD

**Issue by tkasarla** [visipedia/inat_loc#1]
Thanks for sharing the dataset! Can you share the taxonomy of the hierarchies for this data? Ideally to load with networkx, but if it is not in that format, that should be fine too.

**Comment by macaodha** [comment]
Thanks for your interest!  
  
RE hierarchy, is this what you need:  
`https://github.com/visipedia/inat_loc/tree/main/dataset#class_labels_xtxt`

If useful, the iNat2021 dataset has the taxonomy described for each class in the annotation file e.g. here it is for class 0:  
```
{'id': 0,
 'name': 'Lumbricus terrestris',
 'common_name': 'Common Earthworm',
 'supercategory': 'Animalia',
 'kingdom': 'Animalia',
 'phylum': 'Annelida',
 'class': 'Clitellata',
 'order': 'Haplotaxida',
 'family': 'Lumbricidae',
 'genus': 'Lumbricus',
 'specific_epithet': 'terrestris',
 'image_dir_name': '00000_Animalia_Annelida_Clitellata_Haplotaxida_Lumbricidae_Lumbricus_terrestris'}
```

You just need to download the train or validation json files from here:  
`https://github.com/visipedia/inat_comp/tree/master/2021#data`  

I hope this helps.

**Comment by elijahcole** [comment]
You can also parse this information out of the iNatLoc metadata files described [here](https://github.com/visipedia/inat_loc/tree/main/dataset#metadata), since each image has a label for every tier of the taxonomy. 

Please re-open the issue if this doesn't answer your question!
